default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST", 'localhost') %>

development:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", 'thesis_development') %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", '') %>
test:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", 'thesis_test') %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", 'postgres') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", '') %>

production:
  <<: *default
  database: <%= ENV.fetch("POSTGRES_DATABASE", 'thesis_production') %>
  username: <%= ENV.fetch("POSTGRES_USERNAME", 'thesis_prod') %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD", 'thesis_prod') %>